-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgkUN0FmvYI1LWWqgD
SGTjqDMBGUcjM6fDgSmX6s6HUlegCgYIKoZIzj0DAQehRANCAASOJWve4omnjAKz
tWK+8GrBTNiBKlB/pj9MgfwC22gdGnoT7R8gt10fcZ9vtrKIovaB9crNxjwehRsT
Pl5d8kFv
-----END PRIVATE KEY-----