"""Reusable Decision Log Service.

Builds a structured decision log from a module's workflow_state.
No LLM calls — purely deterministic extraction from confirmed stage data.

Each row represents one item that was either generated by the model or added/edited
by a user, capturing:
  - What was decided (item name, category, stage)
  - Where it came from (model with citation hint vs. user with email)
  - Who confirmed it (always a person, with email from confirmed_by uid + timestamp)

The log is exportable as DOCX or JSON. The DOCX format is a formal audit table.
"""

from __future__ import annotations

from datetime import datetime, timezone
from typing import Any


# ---------------------------------------------------------------------------
# Core builder
# ---------------------------------------------------------------------------

def build_decision_log(
    workflow_state: dict[str, Any],
    stage_defs: list,  # list[StageDef] — avoid importing to keep this service portable
    project_context: dict[str, Any] | None = None,
    current_user_email: str | None = None,
) -> dict[str, Any]:
    """Build a structured decision log from workflow_state.

    Returns a dict with 'metadata' and 'decisions' (list of decision entries).
    Each decision entry is a flat dict safe to render or export.
    """
    stage_id_to_title = {s.id: s.title for s in stage_defs}
    decisions: list[dict[str, Any]] = []

    for stage_id, stage_state in workflow_state.get("stages", {}).items():
        if stage_state.get("status") not in ("confirmed", "draft"):
            continue

        stage_title = stage_id_to_title.get(stage_id, stage_id)
        stage_data = stage_state.get("data") or {}
        confirmed_by_uid = stage_state.get("confirmed_by") or ""
        confirmed_at_iso = stage_state.get("confirmed_at") or ""
        confirmed_at_display = _format_ts(confirmed_at_iso)

        # Confirmed_by is stored as a Firebase UID — display as-is unless we have the email.
        # The frontend passes user emails where known; otherwise we show the UID.
        confirmed_by_display = confirmed_by_uid or "—"

        # ── List / table items ──────────────────────────────────────────
        for item in stage_data.get("items", []):
            entry = _build_item_entry(
                item=item,
                stage_title=stage_title,
                confirmed_by_display=confirmed_by_display,
                confirmed_at_display=confirmed_at_display,
            )
            if entry:
                decisions.append(entry)

        # ── Record enrichments ──────────────────────────────────────────
        # Records are per-item enrichments (e.g. stakeholder details).
        # They don't add new named decisions, but we note the enrichment
        # was confirmed for completeness.
        for item_id, record in stage_data.get("records", {}).items():
            if not record:
                continue
            decisions.append({
                "stage": stage_title,
                "name": f"[Enrichment: {item_id[:8]}]",
                "category": "",
                "source_type": "model",
                "source_detail": "model (AI enrichment)",
                "confirmed_by": confirmed_by_display,
                "confirmed_at": confirmed_at_display,
                "notes": _summarize_record(record),
            })

    return {
        "metadata": {
            "project_title": (project_context or {}).get("project_title", ""),
            "generated_at": datetime.now(timezone.utc).isoformat(),
            "generated_by": current_user_email or "system",
            "total_decisions": len(decisions),
        },
        "decisions": decisions,
    }


# ---------------------------------------------------------------------------
# DOCX export
# ---------------------------------------------------------------------------

def build_decision_log_docx(
    workflow_state: dict[str, Any],
    stage_defs: list,
    project_context: dict[str, Any] | None = None,
    current_user_email: str | None = None,
) -> bytes:
    """Build a decision log DOCX from workflow state. No LLM calls."""
    log = build_decision_log(workflow_state, stage_defs, project_context, current_user_email)
    return _render_docx(log)


# ---------------------------------------------------------------------------
# Private helpers
# ---------------------------------------------------------------------------

def _build_item_entry(
    item: dict[str, Any],
    stage_title: str,
    confirmed_by_display: str,
    confirmed_at_display: str,
) -> dict[str, Any] | None:
    content = item.get("content", {})
    provenance = item.get("provenance", {})
    origin = item.get("origin", "")
    derivation = (provenance.get("derivation") or "").lower()

    # Primary display name: try common field names
    name = (
        content.get("name")
        or content.get("label")
        or content.get("variable")
        or content.get("title")
        or ""
    )
    if not name:
        return None

    category = content.get("category") or content.get("label") or ""

    # Source classification
    is_user = "user" in derivation or "user" in (origin or "").lower()

    if is_user:
        source_type = "user"
        user_email = provenance.get("user_email") or ""
        source_detail = f"user: {user_email}" if user_email else "user added"
    else:
        source_type = "model"
        sources = provenance.get("sources", []) or []
        if sources:
            cited = ", ".join(
                s.get("title") or s.get("url") or ""
                for s in sources[:3]
                if s.get("title") or s.get("url")
            )
            source_detail = f"model (cited: {cited})" if cited else "model"
        else:
            source_detail = "model (training data)"

    return {
        "stage": stage_title,
        "name": name,
        "category": category,
        "source_type": source_type,
        "source_detail": source_detail,
        "confirmed_by": confirmed_by_display,
        "confirmed_at": confirmed_at_display,
        "notes": "",
    }


def _format_ts(iso_str: str) -> str:
    if not iso_str:
        return "—"
    try:
        dt = datetime.fromisoformat(iso_str.replace("Z", "+00:00"))
        return dt.strftime("%d %b %Y %H:%M UTC")
    except Exception:
        return iso_str


def _summarize_record(record: dict[str, Any]) -> str:
    parts = []
    for key in ("influence_level", "impact_level", "engagement_priority", "role_in_project"):
        val = record.get(key)
        if val:
            parts.append(f"{key.replace('_', ' ').title()}: {val}")
    return "; ".join(parts[:4])


def _render_docx(log: dict[str, Any]) -> bytes:
    """Render a decision log dict as a DOCX audit table."""
    try:
        from docx import Document
        from docx.shared import Pt, RGBColor, Inches
        from docx.oxml.ns import qn
        from docx.enum.text import WD_ALIGN_PARAGRAPH
    except ImportError as exc:
        raise RuntimeError("python-docx is required for DOCX export") from exc

    doc = Document()

    # Title
    meta = log.get("metadata", {})
    title_para = doc.add_paragraph()
    title_para.alignment = WD_ALIGN_PARAGRAPH.LEFT
    run = title_para.add_run(f"Decision Log — {meta.get('project_title', 'Project')}")
    run.bold = True
    run.font.size = Pt(16)

    # Metadata block
    gen_at = _format_ts(meta.get("generated_at", ""))
    gen_by = meta.get("generated_by", "system")
    meta_para = doc.add_paragraph(
        f"Generated: {gen_at}  ·  By: {gen_by}  ·  {meta.get('total_decisions', 0)} entries"
    )
    meta_para.runs[0].font.size = Pt(9)
    meta_para.runs[0].font.color.rgb = RGBColor(0x6B, 0x72, 0x80)

    doc.add_paragraph()

    # Table
    decisions = log.get("decisions", [])
    if not decisions:
        doc.add_paragraph("No confirmed decisions found.")
    else:
        headers = ["Stage", "Item", "Category", "Source", "Source Detail", "Confirmed By", "Confirmed At"]
        col_widths = [1.0, 2.0, 1.4, 0.8, 2.2, 1.4, 1.2]  # inches

        table = doc.add_table(rows=1, cols=len(headers))
        table.style = "Table Grid"

        # Header row
        hdr_cells = table.rows[0].cells
        for i, (header, width) in enumerate(zip(headers, col_widths)):
            hdr_cells[i].width = Inches(width)
            para = hdr_cells[i].paragraphs[0]
            run = para.add_run(header)
            run.bold = True
            run.font.size = Pt(9)
            # Header background
            tc = hdr_cells[i]._tc
            tcPr = tc.get_or_add_tcPr()
            shd = tc.get_or_add_tcPr().get_or_add_shd()
            shd.set(qn("w:fill"), "005E72")
            shd.set(qn("w:color"), "auto")
            para.runs[0].font.color.rgb = RGBColor(0xFF, 0xFF, 0xFF)

        # Data rows
        for decision in decisions:
            row_cells = table.add_row().cells
            values = [
                decision.get("stage", ""),
                decision.get("name", ""),
                decision.get("category", ""),
                decision.get("source_type", ""),
                decision.get("source_detail", ""),
                decision.get("confirmed_by", ""),
                decision.get("confirmed_at", ""),
            ]
            for i, (val, width) in enumerate(zip(values, col_widths)):
                row_cells[i].width = Inches(width)
                para = row_cells[i].paragraphs[0]
                run = para.add_run(str(val))
                run.font.size = Pt(8.5)

    import io
    buf = io.BytesIO()
    doc.save(buf)
    return buf.getvalue()
