import type { Metadata } from 'next';
import Link from 'next/link';
import { LegalPageShell } from '@/components/legal/LegalPageShell';

export const metadata: Metadata = {
  title: 'Terms of Service — Nitrogen AI',
};

const LAST_UPDATED = '2026-07-21';

/**
 * Mirrors the canonical copy in /TERMS.md at the repo root. Keep both in sync —
 * the markdown file is the GitHub-visible source, this page is the in-app / public link target.
 */
export default function TermsPage() {
  return (
    <LegalPageShell title="Terms of Service" lastUpdated={LAST_UPDATED}>
      <p>
        These Terms of Service (&quot;Terms&quot;) govern access to and use of the hosted Nitrogen AI product at{' '}
        <code>app.the-nitrogen.ai</code> and related subdomains (the &quot;Service&quot;). If you use a self-hosted
        deployment of the open-source Nitrogen AI codebase instead, these Terms do not apply to you — see the
        project&apos;s LICENSE, COMMERCIAL_LICENSE.md, and docs/forking.md on{' '}
        <a href="https://github.com/nicholasrossano/nitrogen" target="_blank" rel="noopener noreferrer">
          GitHub
        </a>
        .
      </p>
      <p>
        By creating an account or otherwise using the Service, you agree to these Terms. If you&apos;re using the
        Service on behalf of an organization, you&apos;re agreeing on that organization&apos;s behalf and confirming
        you have authority to do so.
      </p>

      <h2>1. The Service</h2>
      <p>
        Nitrogen AI is a chat-first diligence and technical-assistance tool. It helps you organize project materials,
        generate structured plans, run AI-assisted assessments, and export documents based on evidence you provide.
        The Service uses large language models and other automated systems to generate content, which can be
        incomplete, outdated, or incorrect.
      </p>

      <h2>2. Accounts</h2>
      <p>
        You&apos;re responsible for your account credentials and for all activity under your account. Tell us
        promptly if you suspect unauthorized access. You must provide accurate information and keep it up to date.
      </p>

      <h2>3. Acceptable use</h2>
      <p>You agree not to:</p>
      <ul>
        <li>use the Service to violate any law or third party&apos;s rights;</li>
        <li>
          upload content you don&apos;t have the right to upload, or that infringes intellectual property, privacy,
          or other rights;
        </li>
        <li>attempt to circumvent usage limits, security controls, or access restrictions;</li>
        <li>
          use the Service to build a directly competing product using data obtained through the Service in
          violation of these Terms;
        </li>
        <li>
          misrepresent AI-generated output as independently verified fact when sharing it outside your organization.
        </li>
      </ul>

      <h2>4. Not investment, financial, legal, or tax advice</h2>
      <p>
        <strong>This is the most important section of these Terms.</strong> Nitrogen AI is a research and
        diligence-support tool, not an adviser.
      </p>
      <ul>
        <li>
          Nitrogen AI is <strong>not a registered investment adviser, broker-dealer, or provider of investment,
          financial, legal, or tax advice</strong>, and nothing generated by the Service — including project plans,
          assessments, status ratings, memos, recommendations (e.g. &quot;proceed / hold / reject&quot;),
          or any other output — <strong>constitutes investment advice, a recommendation to buy, sell, or hold any
          investment, or an offer or solicitation of any kind.</strong>
        </li>
        <li>
          All outputs are AI-assisted drafts intended to support your own diligence process. They may be incomplete,
          contain errors, misinterpret source documents, or omit material facts.{' '}
          <strong>
            You are solely responsible for independently verifying any information before relying on it or sharing
            it with investors, donors, lenders, regulators, or any other third party.
          </strong>
        </li>
        <li>
          Before making any investment, funding, or business decision, consult qualified, licensed professionals
          (investment, legal, tax, technical, or otherwise) as appropriate.
        </li>
        <li>We are not liable for decisions made, or losses incurred, in reliance on output generated by the Service.</li>
      </ul>

      <h2>5. Your content</h2>
      <p>
        You retain ownership of the documents, evidence, and other content you upload (&quot;Your Content&quot;). You
        grant us a license to host, process, and transmit Your Content solely to provide and improve the Service
        (including sending relevant excerpts to third-party AI model providers as described in the{' '}
        <Link href="/legal/privacy">Privacy Policy</Link>). You represent that you have the right to upload Your
        Content and grant this license.
      </p>

      <h2>6. Subscriptions and billing</h2>
      <p>
        Paid tiers are billed as described at checkout and in-app. Fees are non-refundable except as required by law
        or as we otherwise state in writing. We may change pricing with advance notice; continued use after a price
        change takes effect constitutes acceptance.
      </p>

      <h2>7. Disclaimers</h2>
      <p>
        THE SERVICE AND ALL OUTPUT ARE PROVIDED &quot;AS IS&quot; AND &quot;AS AVAILABLE,&quot; WITHOUT WARRANTIES OF
        ANY KIND, EXPRESS OR IMPLIED, INCLUDING MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE,
        NON-INFRINGEMENT, AND ACCURACY. WE DO NOT WARRANT THAT THE SERVICE WILL BE UNINTERRUPTED, ERROR-FREE, OR
        THAT AI-GENERATED OUTPUT WILL BE ACCURATE OR COMPLETE.
      </p>

      <h2>8. Limitation of liability</h2>
      <p>
        TO THE MAXIMUM EXTENT PERMITTED BY LAW, WE ARE NOT LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL,
        CONSEQUENTIAL, OR PUNITIVE DAMAGES, OR ANY LOSS OF PROFITS, REVENUE, DATA, OR INVESTMENT VALUE, ARISING FROM
        YOUR USE OF THE SERVICE OR RELIANCE ON ITS OUTPUT, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. OUR
        TOTAL LIABILITY FOR ANY CLAIM RELATING TO THE SERVICE WILL NOT EXCEED THE AMOUNT YOU PAID US IN THE 12
        MONTHS BEFORE THE CLAIM AROSE.
      </p>

      <h2>9. Termination</h2>
      <p>
        You may stop using the Service and delete your account at any time from Settings. We may suspend or
        terminate access for violation of these Terms, non-payment, or to protect the Service or other users.
      </p>

      <h2>10. Changes to these Terms</h2>
      <p>
        We may update these Terms from time to time. We&apos;ll post the updated version here with a new &quot;Last
        updated&quot; date. Continued use after changes take effect constitutes acceptance.
      </p>

      <h2>11. Governing law</h2>
      <p>
        <em>[Placeholder — governing jurisdiction to be specified with counsel.]</em>
      </p>

      <h2>12. Contact</h2>
      <p>
        Questions about these Terms: <a href="mailto:nicholas.rossano@gmail.com">nicholas.rossano@gmail.com</a>.
      </p>
    </LegalPageShell>
  );
}
