-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg9hbi2SM4XlBkhlCL
FuQQ4lppuJIdlUzOsJ38quP5E5OgCgYIKoZIzj0DAQehRANCAAR/sLIHgUDnqvyP
ryjbxzEsmaQZBEKdfxB7s3ystmV3+oiV2vcf/oGPcvA+05YRShP5tF8ExZ7L5ceL
KU3H5ypo
-----END PRIVATE KEY-----