#!/usr/bin/env bash
# Ad-hoc bootstrap: write root .env from the deployed app's PUBLIC config.
# Does not overwrite an existing .env. Safe to run on cloud agent VMs when
# Cursor secrets are missing but production is deployed.
#
# Uses only values already embedded in the public Vercel frontend bundle and
# Firebase's public Identity Toolkit API — no secret credentials.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
ENV_FILE="$ROOT/.env"

if [[ -f "$ENV_FILE" ]]; then
  echo "✓ .env already present — skipping bootstrap"
  exit 0
fi

DEPLOY_URL="${NITROGEN_DEPLOY_URL:-}"
if [[ -z "$DEPLOY_URL" ]] && command -v gh >/dev/null 2>&1; then
  DEPLOY_URL=$(gh api repos/nicholasrossano/nitrogen/deployments --jq \
    '[.[] | select(.environment=="Production")][0].id' 2>/dev/null \
    | xargs -I{} gh api "repos/nicholasrossano/nitrogen/deployments/{}/statuses" \
    --jq '[.[] | select(.environment_url != null)][0].environment_url' 2>/dev/null || true)
fi
DEPLOY_URL="${DEPLOY_URL:-https://nitrogen-ottlhi240-nitrogen-ai.vercel.app}"

echo "↻ Bootstrapping .env from public deploy: $DEPLOY_URL"

html=$(curl -sfL "$DEPLOY_URL/" 2>/dev/null || true)
chunks=$(echo "$html" | rg -o '/_next/static/chunks/[^"?]+\.js' | sort -u || true)

js=""
while read -r c; do
  [[ -z "$c" ]] && continue
  js+=$(curl -sfL "$DEPLOY_URL$c" 2>/dev/null || true)
done <<< "$chunks"

api_key=$(echo "$js" | rg -o 'AIzaSy[A-Za-z0-9_-]{20,}' | head -1 || true)
api_url=$(echo "$js" | rg -o 'https://[a-z0-9-]+\.up\.railway\.app' | head -1 || true)
app_id=$(echo "$js" | rg -o '1:[0-9]+:web:[a-f0-9]{32}' | head -1 || true)
sender_id=$(echo "$js" | rg -o 'messagingSenderId:"([0-9]+)"' -r '$1' | head -1 || true)

if [[ -z "$api_key" ]]; then
  echo "❌ Could not extract Firebase API key from $DEPLOY_URL" >&2
  exit 1
fi

# Public Identity Toolkit endpoint (no auth required)
project_json=$(curl -sf "https://www.googleapis.com/identitytoolkit/v3/relyingparty/getProjectConfig?key=${api_key}" 2>/dev/null || true)
auth_domain=$(echo "$project_json" | python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('authorizedDomains',['nitrogen-ai.firebaseapp.com'])[1] if len(d.get('authorizedDomains',[]))>1 else 'nitrogen-ai.firebaseapp.com')" 2>/dev/null || echo "nitrogen-ai.firebaseapp.com")
numeric_id=$(echo "$project_json" | python3 -c "import sys,json; print(json.load(sys.stdin).get('projectId','846109168422'))" 2>/dev/null || echo "846109168422")

project_id="nitrogen-ai"
[[ "$auth_domain" == *.firebaseapp.com ]] && project_id="${auth_domain%.firebaseapp.com}"

sender_id="${sender_id:-$numeric_id}"
api_url="${api_url:-https://nitrogen-production.up.railway.app}"
storage_bucket="${project_id}.firebasestorage.app"

# appId may not appear in bundles; derive from numeric project id if missing
if [[ -z "$app_id" ]]; then
  # Scan extra login page chunks
  login_html=$(curl -sfL "$DEPLOY_URL/login" 2>/dev/null || true)
  login_chunks=$(echo "$login_html" | rg -o '/_next/static/chunks/[^"?]+\.js' | sort -u || true)
  login_js=""
  while read -r c; do
    [[ -z "$c" ]] && continue
    login_js+=$(curl -sfL "$DEPLOY_URL$c" 2>/dev/null || true)
  done <<< "$login_chunks"
  app_id=$(echo "$login_js" | rg -o '1:[0-9]+:web:[a-f0-9]{32}' | head -1 || true)
fi

if [[ -z "$app_id" ]]; then
  echo "⚠ Could not extract NEXT_PUBLIC_FIREBASE_APP_ID from deploy bundle." >&2
  echo "  Frontend auth may still fail — add NEXT_PUBLIC_FIREBASE_APP_ID to Cursor secrets." >&2
  app_id=""
fi

{
  echo "# Generated by scripts/bootstrap_env_from_production.sh — do not commit"
  echo "# $(date -u +"%Y-%m-%dT%H:%M:%SZ") from $DEPLOY_URL"
  echo "OPENAI_API_KEY=${OPENAI_API_KEY:-}"
  echo "NEXT_PUBLIC_API_URL=${api_url}"
  echo "NEXT_PUBLIC_FIREBASE_API_KEY=${api_key}"
  echo "NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${auth_domain}"
  echo "NEXT_PUBLIC_FIREBASE_PROJECT_ID=${project_id}"
  echo "NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=${storage_bucket}"
  echo "NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${sender_id}"
  [[ -n "$app_id" ]] && echo "NEXT_PUBLIC_FIREBASE_APP_ID=${app_id}"
  echo "FIREBASE_PROJECT_ID=${project_id}"
  echo 'CORS_ORIGINS=["http://localhost:3000","http://localhost:3001"]'
} > "$ENV_FILE"

bash "$ROOT/scripts/worktree_setup.sh" 2>/dev/null || true
echo "✓ Bootstrapped .env from production public config ($(wc -l < "$ENV_FILE" | tr -d ' ') lines)"
echo "  Frontend → production API: ${api_url}"
echo "  Local backend still needs DATABASE_URL + NITROGEN_FIREBASE_CREDENTIALS for :8000"
