#!/usr/bin/env bash
# Resolve root .env for local dev without overwriting an existing file.
#
# Resolution order:
#   1. Keep repo-root .env if it already exists
#   2. Symlink NITROGEN_ENV_FILE when that path exists (cloud VM / CI mount)
#   3. Materialize .env from whitelisted process environment variables
#
# Never copies .env.example — empty Firebase placeholders break login.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
ENV_FILE="$ROOT/.env"

if [[ -f "$ENV_FILE" ]]; then
  echo "✓ .env already present"
  exit 0
fi

if [[ -n "${NITROGEN_ENV_FILE:-}" && -f "${NITROGEN_ENV_FILE}" ]]; then
  ln -sfn "$(readlink -f "${NITROGEN_ENV_FILE}")" "$ENV_FILE"
  echo "✓ Linked .env from NITROGEN_ENV_FILE=${NITROGEN_ENV_FILE}"
  exit 0
fi

try_vercel_env_pull() {
  if [[ -z "${VERCEL_TOKEN:-}" ]]; then
    return 1
  fi
  if ! command -v npx >/dev/null 2>&1; then
    return 1
  fi

  local pull_args=(env pull "$ENV_FILE" --yes --environment="${VERCEL_ENV:-development}")
  if [[ -n "${VERCEL_TOKEN:-}" ]]; then
    pull_args+=(--token="$VERCEL_TOKEN")
  fi
  if [[ -n "${VERCEL_ORG_ID:-}" && -n "${VERCEL_PROJECT_ID:-}" ]]; then
    pull_args+=(--scope="$VERCEL_ORG_ID" --project="$VERCEL_PROJECT_ID")
  fi

  echo "↻ Pulling dev env from Vercel (same vars as your deployed frontend)…"
  if (cd "$ROOT" && npx --yes vercel@latest "${pull_args[@]}" >/dev/null); then
    if [[ -f "$ENV_FILE" ]]; then
      echo "✓ Pulled .env from Vercel (${VERCEL_ENV:-development})"
      return 0
    fi
  fi
  rm -f "$ENV_FILE"
  return 1
}

if try_vercel_env_pull; then
  exit 0
fi

# Whitelist only — do not dump the entire environment into .env.
ENV_KEYS=(
  DATABASE_URL
  OPENAI_API_KEY
  STORAGE_TYPE
  EXPORTS_DIR
  FIREBASE_STORAGE_BUCKET
  FIREBASE_PROJECT_ID
  NITROGEN_FIREBASE_CREDENTIALS
  FIREBASE_SERVICE_ACCOUNT_JSON
  PVWATTS_API_KEY
  IATI_API_KEY
  WORLDBANK_API_BASE
  WORLDBANK_SEARCH_BASE
  DEBUG
  CORS_ORIGINS
  GOOGLE_CLIENT_ID
  GOOGLE_CLIENT_SECRET
  GOOGLE_REDIRECT_URI
  FRONTEND_URL
  BILLING_TESTING_MODE
  STRIPE_SECRET_KEY
  STRIPE_WEBHOOK_SECRET
  STRIPE_STARTER_PRICE_ID
  STRIPE_PRO_PRICE_ID
  TRIAL_MESSAGE_LIMIT
  TRIAL_COST_LIMIT_USD
  ACCESS_CODE
  STARTER_USAGE_LIMIT_USD
  PRO_USAGE_LIMIT_USD
  API_KEY_ENCRYPTION_KEY
  NEXT_PUBLIC_API_URL
  NEXT_PUBLIC_ACCESS_CODE
  NEXT_PUBLIC_FIREBASE_API_KEY
  NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
  NEXT_PUBLIC_FIREBASE_PROJECT_ID
  NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
  NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
  NEXT_PUBLIC_FIREBASE_APP_ID
  NEXT_PUBLIC_GOOGLE_CLIENT_ID
  NEXT_PUBLIC_GOOGLE_PROJECT_NUMBER
  NEXT_PUBLIC_GOOGLE_API_KEY
  NEXT_PUBLIC_STRIPE_STARTER_PRICE_ID
  NEXT_PUBLIC_STRIPE_PRO_PRICE_ID
)

missing_required=()
for key in DATABASE_URL NEXT_PUBLIC_FIREBASE_API_KEY FIREBASE_PROJECT_ID; do
  if [[ -z "${!key:-}" ]]; then
    missing_required+=("$key")
  fi
done

if [[ ${#missing_required[@]} -gt 0 ]]; then
  echo "❌ Missing root .env and required environment variables: ${missing_required[*]}"
  echo "   Local: cp .env.example .env and fill values."
  echo "   Vercel (recommended for cloud agents): add VERCEL_TOKEN (+ VERCEL_ORG_ID, VERCEL_PROJECT_ID) as Cursor secrets to auto-pull."
  echo "   Or add individual vars as Cursor secrets, or set NITROGEN_ENV_FILE to a mounted .env path."
  echo "   Note: Vercel/Railway dashboard env applies to deployed apps only — not this VM's localhost dev server."
  exit 1
fi

if [[ -z "${NITROGEN_FIREBASE_CREDENTIALS:-}" && -z "${FIREBASE_SERVICE_ACCOUNT_JSON:-}" ]]; then
  echo "❌ Missing Firebase service account: set NITROGEN_FIREBASE_CREDENTIALS or FIREBASE_SERVICE_ACCOUNT_JSON"
  exit 1
fi

{
  echo "# Generated by scripts/materialize_dev_env.sh — do not commit"
  echo "# $(date -u +"%Y-%m-%dT%H:%M:%SZ")"
  for key in "${ENV_KEYS[@]}"; do
    value="${!key:-}"
    [[ -z "$value" ]] && continue
    printf '%s=%q\n' "$key" "$value"
  done
} > "$ENV_FILE"

echo "✓ Materialized .env from process environment ($(wc -l < "$ENV_FILE" | tr -d ' ') lines)"
