#!/usr/bin/env bash
# Resolve root .env for local dev without ever overwriting an existing file.
#
# Resolution order (stops at first success):
#   1. Existing repo-root .env              → no-op, keep it
#   2. NITROGEN_ENV_FILE path               → symlink it
#   3. VERCEL_TOKEN + VERCEL_PROJECT_ID     → vercel env pull (frontend vars)
#   4. Individual secrets in env            → write whitelisted vars to .env
#
# Never copies .env.example — empty Firebase placeholders break login.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
ENV_FILE="$ROOT/.env"

# ── 1. Already exists ──────────────────────────────────────────
if [[ -f "$ENV_FILE" ]]; then
  echo "✓ .env present"
  exit 0
fi

# ── 2. Mounted env file ────────────────────────────────────────
if [[ -n "${NITROGEN_ENV_FILE:-}" && -f "${NITROGEN_ENV_FILE}" ]]; then
  ln -sfn "$(readlink -f "${NITROGEN_ENV_FILE}")" "$ENV_FILE"
  echo "✓ Linked .env from NITROGEN_ENV_FILE"
  exit 0
fi

# ── 3. Vercel env pull ─────────────────────────────────────────
# Requires Cursor secrets: VERCEL_TOKEN, VERCEL_PROJECT_ID, VERCEL_ORG_ID
# One-time Cursor setup pulls everything Vercel already knows about the project.
try_vercel_pull() {
  [[ -z "${VERCEL_TOKEN:-}" ]]      && return 1
  [[ -z "${VERCEL_PROJECT_ID:-}" ]] && { echo "⚠ VERCEL_TOKEN set but VERCEL_PROJECT_ID missing"; return 1; }

  # Install Vercel CLI globally if absent (cached after first run)
  if ! command -v vercel >/dev/null 2>&1; then
    echo "↻ Installing Vercel CLI…"
    npm install -g vercel --silent 2>/dev/null || return 1
  fi

  # Write a temporary project link so vercel env pull knows which project
  local vdir="$ROOT/.vercel"
  local vfile="$vdir/project.json"
  local created_vdir=0
  if [[ ! -f "$vfile" ]]; then
    mkdir -p "$vdir"
    printf '{"projectId":"%s","orgId":"%s"}\n' \
      "$VERCEL_PROJECT_ID" "${VERCEL_ORG_ID:-}" > "$vfile"
    created_vdir=1
  fi

  echo "↻ Pulling dev env from Vercel…"
  local ok=0
  if vercel env pull "$ENV_FILE" \
      --token="$VERCEL_TOKEN" \
      --environment=development \
      --yes 2>/dev/null \
    && [[ -s "$ENV_FILE" ]]; then
    ok=1
  fi

  # Always clean up the temp link so we don't pollute the repo
  [[ "$created_vdir" == "1" ]] && rm -rf "$vdir"

  if [[ "$ok" == "1" ]]; then
    echo "✓ Pulled .env from Vercel (development)"
    return 0
  fi
  rm -f "$ENV_FILE"
  return 1
}

if try_vercel_pull; then
  exit 0
fi

# ── 4. Individual secrets from process environment ─────────────
# Works when each var is added individually as a Cursor secret.
ENV_KEYS=(
  DATABASE_URL
  OPENAI_API_KEY
  STORAGE_TYPE
  EXPORTS_DIR
  FIREBASE_STORAGE_BUCKET
  FIREBASE_PROJECT_ID
  NITROGEN_FIREBASE_CREDENTIALS
  FIREBASE_SERVICE_ACCOUNT_JSON
  PVWATTS_API_KEY
  IATI_API_KEY
  WORLDBANK_API_BASE
  WORLDBANK_SEARCH_BASE
  DEBUG
  CORS_ORIGINS
  GOOGLE_CLIENT_ID
  GOOGLE_CLIENT_SECRET
  GOOGLE_REDIRECT_URI
  FRONTEND_URL
  BILLING_TESTING_MODE
  STRIPE_SECRET_KEY
  STRIPE_WEBHOOK_SECRET
  STRIPE_STARTER_PRICE_ID
  STRIPE_PRO_PRICE_ID
  TRIAL_MESSAGE_LIMIT
  TRIAL_COST_LIMIT_USD
  ACCESS_CODE
  STARTER_USAGE_LIMIT_USD
  PRO_USAGE_LIMIT_USD
  API_KEY_ENCRYPTION_KEY
  NEXT_PUBLIC_API_URL
  NEXT_PUBLIC_ACCESS_CODE
  NEXT_PUBLIC_FIREBASE_API_KEY
  NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
  NEXT_PUBLIC_FIREBASE_PROJECT_ID
  NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
  NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
  NEXT_PUBLIC_FIREBASE_APP_ID
  NEXT_PUBLIC_GOOGLE_CLIENT_ID
  NEXT_PUBLIC_GOOGLE_PROJECT_NUMBER
  NEXT_PUBLIC_GOOGLE_API_KEY
  NEXT_PUBLIC_STRIPE_STARTER_PRICE_ID
  NEXT_PUBLIC_STRIPE_PRO_PRICE_ID
)

missing=()
for key in NEXT_PUBLIC_FIREBASE_API_KEY FIREBASE_PROJECT_ID; do
  [[ -z "${!key:-}" ]] && missing+=("$key")
done

if [[ ${#missing[@]} -gt 0 ]]; then
  cat >&2 <<EOF
❌ Cannot configure .env — no usable secret source found.
   Missing: ${missing[*]}

   Fix (pick one — one-time setup):
   A) Vercel pull  — add Cursor secrets: VERCEL_TOKEN, VERCEL_PROJECT_ID, VERCEL_ORG_ID
   B) Mirror vars  — add each var below as a Cursor secret (same name as .env.example)
   C) Mount file   — set NITROGEN_ENV_FILE=/path/to/your/.env as a Cursor secret
   D) Local dev    — cp .env.example .env && fill values (never commit)

   See docs/self-hosting.md for full setup instructions.
EOF
  exit 1
fi

if [[ -z "${NITROGEN_FIREBASE_CREDENTIALS:-}" && -z "${FIREBASE_SERVICE_ACCOUNT_JSON:-}" ]]; then
  echo "❌ Firebase service account missing: add NITROGEN_FIREBASE_CREDENTIALS or FIREBASE_SERVICE_ACCOUNT_JSON as a Cursor secret." >&2
  exit 1
fi

{
  echo "# Generated by scripts/materialize_dev_env.sh — do not commit"
  echo "# $(date -u +"%Y-%m-%dT%H:%M:%SZ")"
  for key in "${ENV_KEYS[@]}"; do
    value="${!key:-}"
    [[ -z "$value" ]] && continue
    printf '%s=%q\n' "$key" "$value"
  done
} > "$ENV_FILE"

echo "✓ Materialized .env from Cursor secrets ($(wc -l < "$ENV_FILE" | tr -d ' ') vars)"
