#!/usr/bin/env bash
# Upsert Nitrogen production Stripe secrets (Railway *_NITROGEN only) into local .env.
#
# CRITICAL: Stripe keys MUST use the _NITROGEN suffix on Railway and Cursor
# Secrets. Never create or sync unsuffixed STRIPE_SECRET_KEY / STRIPE_PRICE_ID /
# STRIPE_WEBHOOK_SECRET there — only STRIPE_*_NITROGEN is valid for this app.
#
# materialize_dev_env.sh never updates an existing .env, so without this script
# a stale/placeholder key sticks forever. This runs on every
# `dev_daemon.sh start|restart` / `setup.sh` when Railway CLI is linked.
#
# Usage:
#   bash scripts/sync_prod_secrets_to_local.sh
#   bash scripts/sync_prod_secrets_to_local.sh --check
#
# Never prints secret values — only key names + prefixes/lengths.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
ENV_FILE="$ROOT/.env"
CHECK_ONLY=0
[[ "${1:-}" == "--check" ]] && CHECK_ONLY=1

if ! command -v railway >/dev/null 2>&1; then
  echo "⚠ railway CLI not found — skipping prod secret sync"
  exit 0
fi

if ! railway status >/dev/null 2>&1; then
  echo "⚠ railway not linked/authenticated — skipping prod secret sync"
  exit 0
fi

TMP="$(mktemp)"
trap 'rm -f "$TMP"' EXIT

if ! railway variables --service nitrogen --kv >"$TMP" 2>/dev/null; then
  if ! railway variables --kv >"$TMP" 2>/dev/null; then
    echo "⚠ could not read Railway variables — skipping prod secret sync"
    exit 0
  fi
fi

# ONLY read *_NITROGEN Stripe keys from Railway. Never fall back to plain names.
get_nitrogen() {
  grep -E "^${1}=" "$TMP" | head -1 | cut -d= -f2- || true
}

# Guardrails (unsuffixed keys + placeholder secret/price) — shared with unit tests.
if ! python3 "$ROOT/scripts/stripe_secret_guards.py" --check-kv "$TMP"; then
  echo "   Delete unsuffixed keys: railway variable delete <KEY> --service nitrogen" >&2
  echo "   Keep only STRIPE_*_NITROGEN." >&2
  exit 1
fi

SECRET="$(get_nitrogen STRIPE_SECRET_KEY_NITROGEN)"
PRICE="$(get_nitrogen STRIPE_PRICE_ID_NITROGEN)"
WHSEC="$(get_nitrogen STRIPE_WEBHOOK_SECRET_NITROGEN)"
PUBLISHABLE="$(get_nitrogen STRIPE_PUBLISHABLE_KEY_NITROGEN)"
OPENAI="$(get_nitrogen OPENAI_API_KEY_NITROGEN)"
# OpenAI may be plain or *_NITROGEN; Stripe must be *_NITROGEN only.
[[ -z "$OPENAI" ]] && OPENAI="$(get_nitrogen OPENAI_API_KEY)"

echo "→ Railway *_NITROGEN billing secrets (presence only):"
if [[ -n "$SECRET" ]]; then
  echo "  STRIPE_SECRET_KEY_NITROGEN     prefix=${SECRET:0:10}… len=${#SECRET}"
else
  echo "  STRIPE_SECRET_KEY_NITROGEN     MISSING"
fi
if [[ -n "$PRICE" ]]; then
  echo "  STRIPE_PRICE_ID_NITROGEN       prefix=${PRICE:0:10}… len=${#PRICE}"
else
  echo "  STRIPE_PRICE_ID_NITROGEN       MISSING"
fi
if [[ -n "$WHSEC" ]]; then
  echo "  STRIPE_WEBHOOK_SECRET_NITROGEN prefix=${WHSEC:0:8}… len=${#WHSEC}"
else
  echo "  STRIPE_WEBHOOK_SECRET_NITROGEN MISSING"
fi

if [[ "$CHECK_ONLY" == "1" ]]; then
  echo "✓ --check OK (Railway has live STRIPE_*_NITROGEN secret + price)"
  exit 0
fi

if [[ ! -f "$ENV_FILE" ]]; then
  echo "# Generated by scripts/sync_prod_secrets_to_local.sh — do not commit" >"$ENV_FILE"
  echo "# $(date -u +"%Y-%m-%dT%H:%M:%SZ")" >>"$ENV_FILE"
fi

# Local .env: write *_NITROGEN as the source of truth. Also mirror onto the
# plain names LOCALLY only so AliasChoices / older tooling see the same live
# values (.env is gitignored). Never push plain Stripe names to Railway or Cursor.
python3 - <<'PY' "$ENV_FILE" "$SECRET" "$PRICE" "$WHSEC" "$OPENAI" "$PUBLISHABLE"
import sys
from pathlib import Path

env_path = Path(sys.argv[1])
secret, price, whsec, openai, publishable = sys.argv[2:7]
text = env_path.read_text() if env_path.exists() else ""

# Canonical shared names are always *_NITROGEN.
updates: dict[str, str] = {
    "STRIPE_SECRET_KEY_NITROGEN": secret,
    "STRIPE_PRICE_ID_NITROGEN": price,
    # Local-only mirrors (same Nitrogen live values) so config AliasChoices
    # and check_secrets keep working if they read the plain name second.
    "STRIPE_SECRET_KEY": secret,
    "STRIPE_PRICE_ID": price,
    "NEXT_PUBLIC_BILLING_ENABLED": "true",
    "NEXT_PUBLIC_STRIPE_PRICE_ID": price,
}
if whsec:
    updates["STRIPE_WEBHOOK_SECRET_NITROGEN"] = whsec
    updates["STRIPE_WEBHOOK_SECRET"] = whsec
if openai:
    updates["OPENAI_API_KEY_NITROGEN"] = openai
    updates["OPENAI_API_KEY"] = openai
if publishable:
    updates["STRIPE_PUBLISHABLE_KEY_NITROGEN"] = publishable
    updates["NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY"] = publishable

lines = text.splitlines()
seen: set[str] = set()
out: list[str] = []
for line in lines:
    if "=" in line and not line.lstrip().startswith("#"):
        key = line.split("=", 1)[0].strip()
        if key in updates:
            out.append(f"{key}={updates[key]}")
            seen.add(key)
            continue
    out.append(line)

missing = [k for k in updates if k not in seen]
if missing:
    out.append("")
    out.append("# Synced from Railway STRIPE_*_NITROGEN by scripts/sync_prod_secrets_to_local.sh")
    for k in missing:
        out.append(f"{k}={updates[k]}")

env_path.write_text("\n".join(out) + ("\n" if out else ""))
print(f"✓ Upserted {len(updates)} keys into {env_path} from Railway *_NITROGEN ({len(missing)} newly appended)")
PY

echo "→ Local .env after sync (presence only):"
grep -E '^(STRIPE_|NEXT_PUBLIC_BILLING|NEXT_PUBLIC_STRIPE|OPENAI_API_KEY)' "$ENV_FILE" \
  | while IFS= read -r line; do
      key="${line%%=*}"; val="${line#*=}"
      echo "  $key prefix=${val:0:10}… len=${#val}"
    done

echo "✓ Local .env mirrors Railway STRIPE_*_NITROGEN (plain names are local mirrors only)"
