import { 
  FileText, 
  CheckSquare,
  Sun,
  Droplet,
  Droplets,
  Zap,
  Sprout,
  Factory,
  Heart,
  School,
  Building,
  Building2,
  Wind,
  Lightbulb,
  TreePine,
  Trees,
  Fish,
  Truck,
  Store,
  Home,
  Users,
  DollarSign,
  Recycle,
  Flame,
  Battery,
  BatteryCharging,
  Plug,
  Plug2,
  Leaf,
  Waves,
  CloudRain,
  Mountain,
  Wheat,
  Apple,
  Carrot,
  Milk,
  Beef,
  ShoppingCart,
  Package,
  Warehouse,
  Ship,
  Plane,
  Bus,
  Train,
  Car,
  Bike,
  Footprints,
  Radio,
  Smartphone,
  Wifi,
  Globe,
  MapPin,
  Map,
  Compass,
  Navigation,
  Briefcase,
  Calculator,
  BarChart3,
  TrendingUp,
  PiggyBank,
  CreditCard,
  Banknote,
  Coins,
  Wallet,
  Receipt,
  Target,
  Award,
  Trophy,
  Medal,
  Flag,
  Rocket,
  Sparkles,
  Star,
  AlertCircle,
  CheckCircle,
  Info,
  HelpCircle,
  Settings,
  Wrench,
  Hammer,
  Paintbrush,
  Palette,
  BookOpen,
  GraduationCap,
  Library,
  Laptop,
  Monitor,
  Database,
  Server,
  Cloud,
  Lock,
  Shield,
  Eye,
  Stethoscope,
  Pill,
  Utensils,
  Shovel,
  Gem,
  Power,
  PowerOff,
  Antenna,
  Signal,
  Satellite,
  Network,
  Handshake,
  HeartHandshake,
  Scale,
  Tractor,
  CircleDollarSign,
  BadgeDollarSign,
  type LucideIcon,
  FolderOpen,
} from 'lucide-react';

/**
 * Maps icon names from backend to lucide-react icon components
 * This is a curated subset - the LLM can choose from any lucide icon name,
 * and if we don't have it imported, it falls back to FolderOpen
 */
const iconMap: Record<string, LucideIcon> = {
  FileText,
  CheckSquare,
  Sun,
  Droplet,
  Droplets,
  Zap,
  Sprout,
  Factory,
  Heart,
  School,
  Building,
  Building2,
  Wind,
  Lightbulb,
  TreePine,
  Trees,
  Fish,
  Truck,
  Store,
  Home,
  Users,
  DollarSign,
  Recycle,
  Flame,
  Battery,
  BatteryCharging,
  Plug,
  Plug2,
  Leaf,
  Waves,
  CloudRain,
  Mountain,
  Wheat,
  Apple,
  Carrot,
  Milk,
  Beef,
  ShoppingCart,
  Package,
  Warehouse,
  Ship,
  Plane,
  Bus,
  Train,
  Car,
  Bike,
  Footprints,
  Radio,
  Smartphone,
  Wifi,
  Globe,
  MapPin,
  Map,
  Compass,
  Navigation,
  Briefcase,
  Calculator,
  BarChart3,
  TrendingUp,
  PiggyBank,
  CreditCard,
  Banknote,
  Coins,
  Wallet,
  Receipt,
  Target,
  Award,
  Trophy,
  Medal,
  Flag,
  Rocket,
  Sparkles,
  Star,
  AlertCircle,
  CheckCircle,
  Info,
  HelpCircle,
  Settings,
  Wrench,
  Hammer,
  Paintbrush,
  Palette,
  BookOpen,
  GraduationCap,
  Library,
  Laptop,
  Monitor,
  Database,
  Server,
  Cloud,
  Lock,
  Shield,
  Eye,
  Stethoscope,
  Pill,
  Utensils,
  Shovel,
  Gem,
  Power,
  PowerOff,
  Antenna,
  Signal,
  Satellite,
  Network,
  Handshake,
  HeartHandshake,
  Scale,
  Tractor,
  CircleDollarSign,
  BadgeDollarSign,
  FolderOpen,
  // Aliases for common LLM responses that map to existing icons
  SolarPanel: Sun,  // SolarPanel doesn't exist in v0.323, use Sun
  Energy: Zap,
  Water: Droplet,
  Agriculture: Sprout,
  Health: Heart,
  Education: School,
  Finance: DollarSign,
  Transport: Truck,
  Infrastructure: Building,
};

/**
 * Get a lucide-react icon component by name
 * Returns FolderOpen as fallback if icon name not found
 */
export function getIconByName(iconName: string | null | undefined): LucideIcon {
  if (!iconName) return FolderOpen;
  return iconMap[iconName] || FolderOpen;
}

/** Canonical icon names (excludes aliases) for the icon picker */
export const ICON_NAMES: string[] = [
  'FolderOpen', 'FileText', 'Briefcase', 'Rocket', 'Sparkles', 'Star', 'Target', 'Flag',
  'Lightbulb', 'Leaf', 'Sprout', 'TreePine', 'Trees', 'Mountain', 'Waves', 'CloudRain',
  'Sun', 'Droplet', 'Droplets', 'Wind', 'Flame', 'Zap', 'Battery', 'BatteryCharging',
  'Plug', 'Plug2', 'Recycle', 'Globe', 'Map', 'MapPin', 'Compass', 'Navigation',
  'Building', 'Building2', 'Home', 'Store', 'Warehouse', 'Factory', 'School',
  'Heart', 'Stethoscope', 'Pill', 'Users', 'Handshake', 'HeartHandshake', 'Scale',
  'DollarSign', 'Coins', 'Wallet', 'PiggyBank', 'Banknote', 'CreditCard', 'Receipt',
  'TrendingUp', 'BarChart3', 'Calculator', 'CircleDollarSign', 'BadgeDollarSign',
  'Truck', 'Ship', 'Plane', 'Bus', 'Train', 'Car', 'Bike', 'Footprints', 'Tractor',
  'Wheat', 'Apple', 'Carrot', 'Milk', 'Beef', 'Fish', 'Utensils',
  'Package', 'ShoppingCart', 'Gem', 'Shovel',
  'Laptop', 'Monitor', 'Smartphone', 'Wifi', 'Radio', 'Antenna', 'Signal', 'Satellite',
  'Database', 'Server', 'Cloud', 'Network', 'Lock', 'Shield', 'Eye',
  'BookOpen', 'GraduationCap', 'Library', 'Palette', 'Paintbrush',
  'Wrench', 'Hammer', 'Settings', 'Power', 'PowerOff',
  'Award', 'Trophy', 'Medal', 'CheckCircle', 'CheckSquare', 'Info', 'AlertCircle', 'HelpCircle',
];
